### PR TITLE
Introduce thread_sched_algorithm with standard suspend_until(), notif…

### PR DESCRIPTION
**Pull request by nat-goodspeed**
…y().

round_robin, along with pretty much every example program's scheduler except
examples/asio/round_robin.hpp, uses the same suspend_until() / notify()
implementation. It's not a stretch to assume that most Fiber applications that
customize sched_algorithm at all will use the very same implementations as
well. Instead of forcing them to copy/paste from round_robin, allow them to
derive from thread_sched_algorithm.

### CODE REVIEW

**Comment by nat-goodspeed** [comment]
Using thread_sched_algorithm along with sched_algorithm_with_properties<T> requires virtual inheritance so there's only one copy of the sched_algorithm base class in the inheritance diagram. If there are multiple copies, one or more of them will complain about unsatisfied pure virtual methods.

**Comment by olk** [comment]
priority.cpp:91:18: warning: 'priority_scheduler::awakened' hides overloaded virtual function [-Woverloaded-virtual]
    virtual void awakened( boost::fibers::context * ctx, priority_props & props) noexcept {
                 ^
../../../boost/fiber/algorithm.hpp:33:18: note: hidden overloaded virtual function 'boost::fibers::sched_algorithm::awakened' declared here: different number of parameters (1 vs 2)
    virtual void awakened( context *) noexcept = 0;

**Comment by nat-goodspeed** [comment]
On Feb 21, 2016 1:14 PM, "Oliver Kowalke" <notifications@github.com> wrote:

> priority.cpp:91:18: warning: 'priority_scheduler::awakened' hides
overloaded virtual function [-Woverloaded-virtual]
> virtual void awakened( boost::fibers::context * ctx, priority_props &
props) noexcept {
> ^
> ../../../boost/fiber/algorithm.hpp:33:18: note: hidden overloaded virtual
function 'boost::fibers::sched_algorithm::awakened' declared here:
different number of parameters (1 vs 2)
> virtual void awakened( context *) noexcept = 0;

Interesting! I don't see that with GCC 4.9.3 on Ubuntu 14.04.

sched_algorithm declares awakened(context*) as pure virtual.
thread_sched_algorithm does not provide an awakened() override.
sched_algorithm_with_properties_base doesn't either.
sched_algorithm_with_properties<T> provides awakened(context*) as 'final'
and introduces awakened(context*, T&) as pure virtual.
priority_scheduler overrides awakened(context*, priority_props&).

Given the 'final' declaration on
sched_algorithm_with_properties<T>::awakened(context*), I don't care that
priority_scheduler::awakened(context*, priority_props&) hides
awakened(context*).

Is there some syntax I should use to reassure the compiler that things are
as they should be?

**Comment by nat-goodspeed** [comment]
On Feb 21, 2016 2:19 PM, "Nat Goodspeed" <nat@lindenlab.com> wrote:

> Is there some syntax I should use to reassure the compiler that things
are as they should be?

'override' keyword?

**Comment by olk** [comment]
gcc 5.2.1 causes the warnings

**Comment by olk** [comment]
Because this patch conflicts with the actual code I'll close it unmerged.

**Pull request closed without merging**
